# Generated by Django 4.2.2 on 2023-06-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastries', '0002_rename_name_cake_cake_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='add_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
