# Generated by Django 4.2.2 on 2023-06-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastries', '0003_cake_add_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='filling',
            name='cake_types',
            field=models.ManyToManyField(blank=True, to='pastries.caketype'),
        ),
        migrations.AddField(
            model_name='filling',
            name='tastes',
            field=models.ManyToManyField(blank=True, to='pastries.taste'),
        ),
        migrations.AddField(
            model_name='topping',
            name='cake_types',
            field=models.ManyToManyField(blank=True, to='pastries.caketype'),
        ),
        migrations.AddField(
            model_name='topping',
            name='tastes',
            field=models.ManyToManyField(blank=True, to='pastries.taste'),
        ),
    ]
